INFO 2025-01-17 00:59:42,266 autoreload 13328 9472 Watching for file changes with StatReloader
INFO 2025-01-17 12:12:35,641 basehttp 13328 6572 "POST /api/users/login/ HTTP/1.1" 200 95
ERROR 2025-01-17 12:13:11,646 log 13328 6572 Internal Server Error: /api/songs/download/
Traceback (most recent call last):
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django_redis\cache.py", line 31, in _decorator
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django_redis\cache.py", line 98, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django_redis\client\default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 416, in initial
    self.check_throttles(request)
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 359, in check_throttles
    if not throttle.allow_request(request, self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\throttling.py", line 123, in allow_request
    self.history = self.cache.get(self.key, [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django_redis\cache.py", line 91, in get
    value = self._get(key, default, version, client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django_redis\cache.py", line 38, in _decorator
    raise e.__cause__
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django_redis\client\default.py", line 258, in get
    value = client.get(key)
            ^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\redis\client.py", line 1606, in get
    return self.execute_command('GET', name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\redis\client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\redis\connection.py", line 1192, in get_connection
    connection.connect()
  File "D:\Projects\TuneVault\venv\Lib\site-packages\redis\connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.
ERROR 2025-01-17 12:13:11,657 basehttp 13328 6572 "POST /api/songs/download/ HTTP/1.1" 500 152254
INFO 2025-01-17 13:01:47,291 autoreload 10232 4292 Watching for file changes with StatReloader
INFO 2025-01-17 13:02:38,598 autoreload 996 17224 Watching for file changes with StatReloader
INFO 2025-01-17 13:05:05,014 autoreload 19364 1204 Watching for file changes with StatReloader
INFO 2025-01-17 13:05:58,707 autoreload 2952 18020 Watching for file changes with StatReloader
INFO 2025-01-17 13:06:21,383 autoreload 18620 17664 Watching for file changes with StatReloader
INFO 2025-01-17 13:07:07,121 autoreload 11612 13352 Watching for file changes with StatReloader
INFO 2025-01-17 13:07:59,970 autoreload 11612 13352 D:\Projects\TuneVault\tunevault\tunevault\settings.py changed, reloading.
INFO 2025-01-17 13:08:04,559 autoreload 3300 15980 Watching for file changes with StatReloader
INFO 2025-01-17 13:09:56,927 autoreload 6596 18076 Watching for file changes with StatReloader
INFO 2025-01-17 13:11:00,693 autoreload 4932 10948 Watching for file changes with StatReloader
INFO 2025-01-17 13:11:29,008 autoreload 16780 536 Watching for file changes with StatReloader
INFO 2025-01-17 13:12:00,284 autoreload 11600 9448 Watching for file changes with StatReloader
ERROR 2025-01-17 13:17:50,442 log 11600 11324 Internal Server Error: /api/songs/download/
Traceback (most recent call last):
  File "C:\Python 311\Lib\site-packages\django_redis\cache.py", line 29, in _decorator
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django_redis\cache.py", line 99, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django_redis\client\default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python 311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python 311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python 311\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Python 311\Lib\site-packages\rest_framework\views.py", line 416, in initial
    self.check_throttles(request)
  File "C:\Python 311\Lib\site-packages\rest_framework\views.py", line 359, in check_throttles
    if not throttle.allow_request(request, self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\throttling.py", line 123, in allow_request
    self.history = self.cache.get(self.key, [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django_redis\cache.py", line 92, in get
    value = self._get(key, default, version, client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django_redis\cache.py", line 36, in _decorator
    raise e.__cause__
  File "C:\Python 311\Lib\site-packages\django_redis\client\default.py", line 258, in get
    value = client.get(key)
            ^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\redis\commands\core.py", line 1822, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\redis\client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\redis\client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\redis\connection.py", line 1422, in get_connection
    connection.connect()
  File "C:\Python 311\Lib\site-packages\redis\connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.
ERROR 2025-01-17 13:17:50,454 basehttp 11600 11324 "POST /api/songs/download/ HTTP/1.1" 500 156242
INFO 2025-01-17 13:18:49,681 basehttp 11600 11324 "POST /api/songs/download/ HTTP/1.1" 201 254
INFO 2025-01-17 13:19:01,796 basehttp 11600 13524 "GET /media/songs/We%20Are%20Infinite.mp3 HTTP/1.1" 200 4454252
WARNING 2025-01-17 13:19:01,845 log 11600 13524 Not Found: /favicon.ico
WARNING 2025-01-17 13:19:01,845 basehttp 11600 13524 "GET /favicon.ico HTTP/1.1" 404 2562
INFO 2025-01-17 13:25:10,710 basehttp 11600 16092 "POST /api/songs/download/ HTTP/1.1" 201 211
INFO 2025-01-17 13:25:16,289 basehttp 11600 20428 "GET /media/songs%5Cyung%20kai%20-%20blue%20(Official%20Music%20Video).mp3 HTTP/1.1" 200 5312492
INFO 2025-01-17 13:46:49,656 autoreload 11600 9448 D:\Projects\TuneVault\tunevault\songs\tasks.py changed, reloading.
INFO 2025-01-17 13:49:57,263 autoreload 12468 20072 Watching for file changes with StatReloader
INFO 2025-01-17 13:50:26,866 autoreload 12468 20072 D:\Projects\TuneVault\tunevault\tunevault\settings.py changed, reloading.
INFO 2025-01-17 13:50:32,950 autoreload 20108 20312 Watching for file changes with StatReloader
INFO 2025-01-17 13:51:53,666 autoreload 20108 20312 D:\Projects\TuneVault\tunevault\tunevault\settings.py changed, reloading.
INFO 2025-01-17 13:52:00,737 autoreload 14972 12480 Watching for file changes with StatReloader
INFO 2025-01-17 13:52:05,134 autoreload 14972 12480 D:\Projects\TuneVault\tunevault\tunevault\settings.py changed, reloading.
INFO 2025-01-17 13:52:12,713 autoreload 708 3132 Watching for file changes with StatReloader
ERROR 2025-01-17 13:52:43,650 views 708 5388 Error during Spotify track download: column "image" of relation "songs_song" does not exist
LINE 1: ...m", "file", "source", "spotify_id", "created_at", "image") V...
                                                             ^
Traceback (most recent call last):
  File "C:\Python 311\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column "image" of relation "songs_song" does not exist
LINE 1: ...m", "file", "source", "spotify_id", "created_at", "image") V...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 125, in download_spotify_track
    song = Song.objects.create(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Python 311\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Python 311\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python 311\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Python 311\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Python 311\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column "image" of relation "songs_song" does not exist
LINE 1: ...m", "file", "source", "spotify_id", "created_at", "image") V...
                                                             ^

ERROR 2025-01-17 13:52:43,768 log 708 5388 Internal Server Error: /api/songs/download/
ERROR 2025-01-17 13:52:43,768 basehttp 708 5388 "POST /api/songs/download/ HTTP/1.1" 500 223
INFO 2025-01-17 13:54:09,426 autoreload 19448 6128 Watching for file changes with StatReloader
INFO 2025-01-17 13:54:41,605 basehttp 19448 17828 "POST /api/songs/download/ HTTP/1.1" 201 211
INFO 2025-01-17 15:29:03,545 basehttp 19448 11716 "POST /api/songs/download/ HTTP/1.1" 201 211
INFO 2025-01-17 15:37:08,415 autoreload 19448 6128 D:\Projects\TuneVault\tunevault\songs\tasks.py changed, reloading.
INFO 2025-01-17 15:37:13,449 autoreload 8048 20104 Watching for file changes with StatReloader
INFO 2025-01-17 15:37:19,005 autoreload 8048 20104 D:\Projects\TuneVault\tunevault\songs\models.py changed, reloading.
INFO 2025-01-17 15:37:22,784 autoreload 18944 15720 Watching for file changes with StatReloader
INFO 2025-01-17 15:39:02,246 autoreload 11940 14364 Watching for file changes with StatReloader
INFO 2025-01-17 15:40:51,750 autoreload 14192 17372 Watching for file changes with StatReloader
INFO 2025-01-17 15:41:28,769 basehttp 14192 23284 "POST /api/songs/download/ HTTP/1.1" 201 323
INFO 2025-01-17 15:43:33,078 basehttp 14192 5212 "GET /media/songs/Old%20Man%20Canyon%20-%20Phantoms%20%26%20Friends%20%5BOfficial%20Video%5D.mp3 HTTP/1.1" 200 5597036
WARNING 2025-01-17 15:43:33,127 log 14192 5212 Not Found: /favicon.ico
INFO 2025-01-17 15:43:33,128 basehttp 14192 5212 - Broken pipe from ('127.0.0.1', 54760)
INFO 2025-01-17 15:58:57,800 autoreload 14192 17372 D:\Projects\TuneVault\tunevault\songs\serializers.py changed, reloading.
INFO 2025-01-17 15:59:02,452 autoreload 20340 22572 Watching for file changes with StatReloader
INFO 2025-01-17 16:28:48,208 autoreload 20340 22572 D:\Projects\TuneVault\tunevault\songs\tasks.py changed, reloading.
INFO 2025-01-17 16:28:52,764 autoreload 22604 21748 Watching for file changes with StatReloader
INFO 2025-01-17 16:29:17,239 autoreload 18356 17936 Watching for file changes with StatReloader
ERROR 2025-01-17 16:29:38,207 views 18356 5864 Unexpected error: 'str' object has no attribute 'url'
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 49, in download
    return self.download_youtube(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 98, in download_youtube
    return Response(serializer.data, status=status.HTTP_201_CREATED)
                    ^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\serializers.py", line 571, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\fields.py", line 1872, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\tunevault\songs\serializers.py", line 19, in get_file_url
    return self.context['request'].build_absolute_uri(obj.file.url)
                                                      ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'url'
ERROR 2025-01-17 16:29:38,274 log 18356 5864 Internal Server Error: /api/songs/download/
ERROR 2025-01-17 16:29:38,274 basehttp 18356 5864 "POST /api/songs/download/ HTTP/1.1" 500 65
INFO 2025-01-17 16:30:38,117 autoreload 18356 17936 D:\Projects\TuneVault\tunevault\songs\serializers.py changed, reloading.
INFO 2025-01-17 16:30:41,879 autoreload 15652 14188 Watching for file changes with StatReloader
INFO 2025-01-17 16:34:18,140 basehttp 15652 21584 "POST /api/songs/download/ HTTP/1.1" 201 265
INFO 2025-01-17 16:38:25,184 basehttp 15652 21988 "POST /api/songs/download/ HTTP/1.1" 201 268
INFO 2025-01-17 16:39:33,570 basehttp 15652 5864 "POST /api/songs/download/ HTTP/1.1" 201 231
INFO 2025-01-17 16:41:52,648 basehttp 15652 22680 "POST /api/songs/download/ HTTP/1.1" 201 231
INFO 2025-01-17 16:51:55,515 autoreload 20688 6096 Watching for file changes with StatReloader
ERROR 2025-01-17 16:52:30,354 views 20688 22668 Unexpected error: null value in column "artist" of relation "songs_song" violates not-null constraint
DETAIL:  Failing row contains (21, Chezile - Beanie (Official Live Video), null, songs\Chezile - Beanie (Official Live Video).mp3, youtube, 2025-01-17 11:22:30.276028+00, 1, , null, null).
Traceback (most recent call last):
  File "C:\Python 311\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NotNullViolation: null value in column "artist" of relation "songs_song" violates not-null constraint
DETAIL:  Failing row contains (21, Chezile - Beanie (Official Live Video), null, songs\Chezile - Beanie (Official Live Video).mp3, youtube, 2025-01-17 11:22:30.276028+00, 1, , null, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 49, in download
    return self.download_youtube(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 89, in download_youtube
    song = Song.objects.create(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Python 311\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Python 311\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python 311\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Python 311\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Python 311\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: null value in column "artist" of relation "songs_song" violates not-null constraint
DETAIL:  Failing row contains (21, Chezile - Beanie (Official Live Video), null, songs\Chezile - Beanie (Official Live Video).mp3, youtube, 2025-01-17 11:22:30.276028+00, 1, , null, null).

ERROR 2025-01-17 16:52:30,509 log 20688 22668 Internal Server Error: /api/songs/download/
ERROR 2025-01-17 16:52:30,510 basehttp 20688 22668 "POST /api/songs/download/ HTTP/1.1" 500 310
INFO 2025-01-17 16:53:18,847 autoreload 20688 6096 D:\Projects\TuneVault\tunevault\songs\tasks.py changed, reloading.
INFO 2025-01-17 16:53:22,601 autoreload 21028 22652 Watching for file changes with StatReloader
INFO 2025-01-17 16:53:38,535 basehttp 21028 6708 "POST /api/songs/download/ HTTP/1.1" 201 231
INFO 2025-01-17 16:56:00,834 autoreload 21028 22652 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 16:56:04,958 autoreload 5904 9180 Watching for file changes with StatReloader
INFO 2025-01-17 16:56:08,987 autoreload 5904 9180 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 16:56:12,991 autoreload 17640 23096 Watching for file changes with StatReloader
INFO 2025-01-17 16:56:18,445 autoreload 17640 23096 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 16:56:22,858 autoreload 4116 7328 Watching for file changes with StatReloader
INFO 2025-01-17 16:56:30,825 autoreload 4116 7328 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 16:56:35,219 autoreload 6968 2940 Watching for file changes with StatReloader
INFO 2025-01-17 16:57:03,631 autoreload 6968 2940 D:\Projects\TuneVault\tunevault\songs\tasks.py changed, reloading.
INFO 2025-01-17 16:57:07,841 autoreload 15496 13176 Watching for file changes with StatReloader
INFO 2025-01-17 16:57:23,144 autoreload 15496 13176 D:\Projects\TuneVault\tunevault\songs\tasks.py changed, reloading.
INFO 2025-01-17 16:57:26,841 autoreload 2908 6932 Watching for file changes with StatReloader
ERROR 2025-01-17 16:57:52,853 views 2908 22264 Unexpected error: name 'cloudinary' is not defined
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 49, in download
    return self.download_youtube(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 89, in download_youtube
    upload_result = cloudinary.uploader.upload(
                    ^^^^^^^^^^
NameError: name 'cloudinary' is not defined
ERROR 2025-01-17 16:57:52,857 log 2908 22264 Internal Server Error: /api/songs/download/
ERROR 2025-01-17 16:57:52,859 basehttp 2908 22264 "POST /api/songs/download/ HTTP/1.1" 500 62
INFO 2025-01-17 16:58:01,301 autoreload 2908 6932 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 16:58:06,066 autoreload 22860 19860 Watching for file changes with StatReloader
INFO 2025-01-17 16:58:49,118 autoreload 1980 18184 Watching for file changes with StatReloader
INFO 2025-01-17 16:59:07,448 autoreload 1980 18184 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 16:59:11,874 autoreload 15812 11976 Watching for file changes with StatReloader
ERROR 2025-01-17 16:59:26,971 views 15812 23152 Validation Error: Must supply api_key
WARNING 2025-01-17 16:59:26,972 log 15812 23152 Bad Request: /api/songs/download/
WARNING 2025-01-17 16:59:26,974 basehttp 15812 23152 "POST /api/songs/download/ HTTP/1.1" 400 31
INFO 2025-01-17 16:59:51,044 autoreload 15812 11976 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 16:59:55,035 autoreload 16736 15696 Watching for file changes with StatReloader
INFO 2025-01-17 17:00:35,145 autoreload 16736 15696 D:\Projects\TuneVault\tunevault\songs\tasks.py changed, reloading.
INFO 2025-01-17 17:00:39,146 autoreload 14428 19032 Watching for file changes with StatReloader
INFO 2025-01-17 17:00:44,558 autoreload 14428 19032 D:\Projects\TuneVault\tunevault\tunevault\settings.py changed, reloading.
INFO 2025-01-17 17:00:48,484 autoreload 17344 21988 Watching for file changes with StatReloader
ERROR 2025-01-17 17:01:04,223 views 17344 14820 Validation Error: Must supply api_key
WARNING 2025-01-17 17:01:04,224 log 17344 14820 Bad Request: /api/songs/download/
WARNING 2025-01-17 17:01:04,225 basehttp 17344 14820 "POST /api/songs/download/ HTTP/1.1" 400 31
INFO 2025-01-17 17:02:14,955 autoreload 17344 21988 D:\Projects\TuneVault\tunevault\songs\tasks.py changed, reloading.
INFO 2025-01-17 17:02:19,674 autoreload 7936 2512 Watching for file changes with StatReloader
INFO 2025-01-17 17:02:24,249 autoreload 7936 2512 D:\Projects\TuneVault\tunevault\songs\tasks.py changed, reloading.
INFO 2025-01-17 17:02:28,458 autoreload 11216 7532 Watching for file changes with StatReloader
INFO 2025-01-17 17:02:38,959 autoreload 11216 7532 D:\Projects\TuneVault\tunevault\songs\tasks.py changed, reloading.
INFO 2025-01-17 17:02:43,335 autoreload 20988 20040 Watching for file changes with StatReloader
INFO 2025-01-17 17:02:59,201 autoreload 20988 20040 D:\Projects\TuneVault\tunevault\songs\tasks.py changed, reloading.
INFO 2025-01-17 17:03:02,972 autoreload 18112 18492 Watching for file changes with StatReloader
INFO 2025-01-17 17:03:09,619 autoreload 18112 18492 D:\Projects\TuneVault\tunevault\songs\tasks.py changed, reloading.
INFO 2025-01-17 17:03:13,370 autoreload 21560 14472 Watching for file changes with StatReloader
INFO 2025-01-17 17:12:45,323 autoreload 23284 15556 Watching for file changes with StatReloader
INFO 2025-01-17 17:13:14,590 autoreload 23284 15556 D:\Projects\TuneVault\tunevault\songs\tasks.py changed, reloading.
INFO 2025-01-17 17:13:19,214 autoreload 21348 13280 Watching for file changes with StatReloader
INFO 2025-01-17 17:13:23,331 autoreload 21348 13280 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 17:13:27,164 autoreload 636 19916 Watching for file changes with StatReloader
INFO 2025-01-17 17:15:09,965 autoreload 636 19916 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 17:15:13,875 autoreload 13300 13428 Watching for file changes with StatReloader
INFO 2025-01-17 17:20:03,561 autoreload 13300 13428 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 17:20:08,034 autoreload 7612 11324 Watching for file changes with StatReloader
INFO 2025-01-17 17:20:19,637 autoreload 7612 11324 D:\Projects\TuneVault\tunevault\tunevault\settings.py changed, reloading.
INFO 2025-01-17 17:20:23,702 autoreload 3228 20308 Watching for file changes with StatReloader
INFO 2025-01-17 17:20:41,851 autoreload 3228 20308 D:\Projects\TuneVault\tunevault\songs\tasks.py changed, reloading.
INFO 2025-01-17 17:20:46,097 autoreload 23172 20536 Watching for file changes with StatReloader
INFO 2025-01-17 17:21:28,918 autoreload 23172 20536 D:\Projects\TuneVault\tunevault\songs\models.py changed, reloading.
INFO 2025-01-17 17:21:32,777 autoreload 7808 12568 Watching for file changes with StatReloader
INFO 2025-01-17 17:21:54,061 basehttp 7808 19940 "POST /api/songs/download/ HTTP/1.1" 200 0
INFO 2025-01-17 17:23:04,760 autoreload 7808 12568 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 17:23:08,862 autoreload 10388 17320 Watching for file changes with StatReloader
INFO 2025-01-17 17:23:23,361 basehttp 10388 19644 "POST /api/songs/download/ HTTP/1.1" 200 214
WARNING 2025-01-17 17:23:27,398 log 10388 21616 Not Found: /media/songs/Chezile
WARNING 2025-01-17 17:23:27,398 basehttp 10388 21616 "GET /media/songs/Chezile HTTP/1.1" 404 2787
WARNING 2025-01-17 17:23:27,479 log 10388 21616 Not Found: /favicon.ico
INFO 2025-01-17 17:23:27,480 basehttp 10388 21616 - Broken pipe from ('127.0.0.1', 56705)
INFO 2025-01-17 17:24:12,048 basehttp 10388 19644 - Broken pipe from ('127.0.0.1', 56695)
INFO 2025-01-17 17:24:19,999 basehttp 10388 11968 "POST /api/songs/download/ HTTP/1.1" 200 229
INFO 2025-01-17 18:17:27,385 basehttp 10388 15732 "POST /api/users/login/ HTTP/1.1" 200 95
INFO 2025-01-17 18:17:30,543 basehttp 10388 15732 "POST /api/users/login/ HTTP/1.1" 200 95
WARNING 2025-01-17 18:31:01,495 log 10388 23204 Unauthorized: /api/songs/
WARNING 2025-01-17 18:31:01,498 log 10388 696 Unauthorized: /api/songs/
WARNING 2025-01-17 18:31:01,498 basehttp 10388 23204 "GET /api/songs/ HTTP/1.1" 401 58
WARNING 2025-01-17 18:31:01,500 basehttp 10388 696 "GET /api/songs/ HTTP/1.1" 401 58
WARNING 2025-01-17 18:38:50,241 log 10388 20560 Unauthorized: /api/songs/download/
WARNING 2025-01-17 18:38:50,242 basehttp 10388 20560 "POST /api/songs/download/ HTTP/1.1" 401 58
WARNING 2025-01-17 18:38:55,141 log 10388 20560 Bad Request: /api/users/login/
WARNING 2025-01-17 18:38:55,142 basehttp 10388 20560 "POST /api/users/login/ HTTP/1.1" 400 68
WARNING 2025-01-17 18:39:07,924 log 10388 20560 Bad Request: /api/users/login/
WARNING 2025-01-17 18:39:07,924 basehttp 10388 20560 "POST /api/users/login/ HTTP/1.1" 400 68
INFO 2025-01-17 18:39:23,454 basehttp 10388 20560 "POST /api/users/login/ HTTP/1.1" 200 95
WARNING 2025-01-17 18:39:23,594 log 10388 20560 Unauthorized: /api/songs/
WARNING 2025-01-17 18:39:23,596 log 10388 23088 Unauthorized: /api/songs/
WARNING 2025-01-17 18:39:23,596 basehttp 10388 20560 "GET /api/songs/ HTTP/1.1" 401 58
WARNING 2025-01-17 18:39:23,597 basehttp 10388 23088 "GET /api/songs/ HTTP/1.1" 401 58
WARNING 2025-01-17 18:39:34,655 log 10388 20560 Unauthorized: /api/songs/download/
WARNING 2025-01-17 18:39:34,658 basehttp 10388 20560 "POST /api/songs/download/ HTTP/1.1" 401 58
INFO 2025-01-17 18:40:02,756 basehttp 10388 20560 "POST /api/users/login/ HTTP/1.1" 200 95
WARNING 2025-01-17 18:40:02,859 log 10388 20560 Unauthorized: /api/songs/
WARNING 2025-01-17 18:40:02,861 log 10388 23088 Unauthorized: /api/songs/
WARNING 2025-01-17 18:40:02,862 basehttp 10388 20560 "GET /api/songs/ HTTP/1.1" 401 58
WARNING 2025-01-17 18:40:02,863 basehttp 10388 23088 "GET /api/songs/ HTTP/1.1" 401 58
WARNING 2025-01-17 18:54:56,683 log 10388 16644 Unauthorized: /api/songs/download/
WARNING 2025-01-17 18:54:56,687 basehttp 10388 16644 "POST /api/songs/download/ HTTP/1.1" 401 58
WARNING 2025-01-17 18:56:02,412 log 10388 16644 Unauthorized: /api/songs/download/
WARNING 2025-01-17 18:56:02,413 basehttp 10388 16644 "POST /api/songs/download/ HTTP/1.1" 401 58
WARNING 2025-01-17 18:58:48,146 log 10388 1404 Unauthorized: /api/songs/download/
WARNING 2025-01-17 18:58:48,148 basehttp 10388 1404 "POST /api/songs/download/ HTTP/1.1" 401 58
WARNING 2025-01-17 19:00:00,400 log 10388 1404 Unauthorized: /api/songs/download/
WARNING 2025-01-17 19:00:00,401 basehttp 10388 1404 "POST /api/songs/download/ HTTP/1.1" 401 58
WARNING 2025-01-17 19:00:33,606 log 10388 1404 Unauthorized: /api/songs/download/
WARNING 2025-01-17 19:00:33,607 basehttp 10388 1404 "POST /api/songs/download/ HTTP/1.1" 401 58
WARNING 2025-01-17 19:00:38,660 log 10388 1404 Bad Request: /api/users/login/
WARNING 2025-01-17 19:00:38,662 basehttp 10388 1404 "POST /api/users/login/ HTTP/1.1" 400 68
WARNING 2025-01-17 19:00:39,018 log 10388 23468 Bad Request: /api/users/login/
WARNING 2025-01-17 19:00:39,020 basehttp 10388 23468 "POST /api/users/login/ HTTP/1.1" 400 68
WARNING 2025-01-17 19:00:39,204 log 10388 18888 Bad Request: /api/users/login/
WARNING 2025-01-17 19:00:39,206 basehttp 10388 18888 "POST /api/users/login/ HTTP/1.1" 400 68
INFO 2025-01-17 19:01:32,852 basehttp 10388 1404 "POST /api/users/login/ HTTP/1.1" 200 95
WARNING 2025-01-17 19:01:33,118 log 10388 1404 Unauthorized: /api/songs/
WARNING 2025-01-17 19:01:33,120 log 10388 23468 Unauthorized: /api/songs/
WARNING 2025-01-17 19:01:33,121 basehttp 10388 1404 "GET /api/songs/ HTTP/1.1" 401 58
WARNING 2025-01-17 19:01:33,121 basehttp 10388 23468 "GET /api/songs/ HTTP/1.1" 401 58
WARNING 2025-01-17 19:03:04,935 log 10388 1404 Unauthorized: /api/songs/download/
WARNING 2025-01-17 19:03:04,937 basehttp 10388 1404 "POST /api/songs/download/ HTTP/1.1" 401 58
WARNING 2025-01-17 19:05:24,546 log 10388 17520 Unauthorized: /api/songs/download/
WARNING 2025-01-17 19:05:24,548 basehttp 10388 17520 "POST /api/songs/download/ HTTP/1.1" 401 58
WARNING 2025-01-17 19:06:46,043 log 10388 17520 Unauthorized: /api/songs/download/
WARNING 2025-01-17 19:06:46,044 basehttp 10388 17520 "POST /api/songs/download/ HTTP/1.1" 401 58
WARNING 2025-01-17 19:06:53,622 log 10388 17520 Unauthorized: /api/songs/download/
WARNING 2025-01-17 19:06:53,623 basehttp 10388 17520 "POST /api/songs/download/ HTTP/1.1" 401 58
WARNING 2025-01-17 19:09:51,094 log 10388 20588 Unauthorized: /api/songs/download/
WARNING 2025-01-17 19:09:51,097 basehttp 10388 20588 "POST /api/songs/download/ HTTP/1.1" 401 58
WARNING 2025-01-17 19:12:32,127 log 10388 20300 Unauthorized: /api/songs/download/
WARNING 2025-01-17 19:12:32,129 basehttp 10388 20300 "POST /api/songs/download/ HTTP/1.1" 401 58
WARNING 2025-01-17 19:16:55,824 log 10388 11984 Unauthorized: /api/songs/download/
WARNING 2025-01-17 19:16:55,825 basehttp 10388 11984 "POST /api/songs/download/ HTTP/1.1" 401 58
WARNING 2025-01-17 19:17:22,546 log 10388 11984 Unauthorized: /api/songs/download/
WARNING 2025-01-17 19:17:22,548 basehttp 10388 11984 "POST /api/songs/download/ HTTP/1.1" 401 58
WARNING 2025-01-17 19:20:23,504 log 10388 17416 Unauthorized: /api/songs/download/
WARNING 2025-01-17 19:20:23,506 basehttp 10388 17416 "POST /api/songs/download/ HTTP/1.1" 401 58
WARNING 2025-01-17 19:20:36,919 log 10388 17416 Unauthorized: /api/songs/download/
WARNING 2025-01-17 19:20:36,920 basehttp 10388 17416 "POST /api/songs/download/ HTTP/1.1" 401 58
INFO 2025-01-17 19:21:26,343 basehttp 10388 22444 "POST /api/songs/download/ HTTP/1.1" 200 214
INFO 2025-01-17 19:22:58,987 autoreload 23444 20116 Watching for file changes with StatReloader
WARNING 2025-01-17 19:23:02,643 log 23444 17748 Unauthorized: /api/songs/download/
WARNING 2025-01-17 19:23:02,644 basehttp 23444 17748 "POST /api/songs/download/ HTTP/1.1" 401 58
WARNING 2025-01-17 19:23:22,049 log 23444 17748 Unauthorized: /api/songs/download/
WARNING 2025-01-17 19:23:22,050 basehttp 23444 17748 "POST /api/songs/download/ HTTP/1.1" 401 58
INFO 2025-01-17 19:25:05,671 basehttp 23444 17748 "POST /api/songs/download/ HTTP/1.1" 200 194
INFO 2025-01-17 19:30:02,153 autoreload 23444 20116 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 19:30:06,357 autoreload 18496 21904 Watching for file changes with StatReloader
INFO 2025-01-17 19:31:05,191 basehttp 18496 19016 "POST /api/songs/download/ HTTP/1.1" 200 4732460
INFO 2025-01-17 19:31:58,700 basehttp 18496 9536 "POST /api/songs/download/ HTTP/1.1" 200 22157612
INFO 2025-01-17 19:45:40,175 autoreload 696 22224 Watching for file changes with StatReloader
INFO 2025-01-17 19:51:04,739 basehttp 696 8048 "POST /api/songs/download/ HTTP/1.1" 200 22157612
INFO 2025-01-17 19:55:11,187 autoreload 696 22224 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 19:55:15,433 autoreload 23488 7092 Watching for file changes with StatReloader
INFO 2025-01-17 19:55:30,193 autoreload 23488 7092 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 19:55:34,439 autoreload 17840 21232 Watching for file changes with StatReloader
INFO 2025-01-17 19:55:42,537 autoreload 17840 21232 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 19:55:47,140 autoreload 22036 14700 Watching for file changes with StatReloader
INFO 2025-01-17 19:56:03,151 autoreload 22036 14700 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 19:56:07,042 autoreload 12788 1748 Watching for file changes with StatReloader
INFO 2025-01-17 19:56:40,734 autoreload 12788 1748 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 19:56:44,769 autoreload 6336 8592 Watching for file changes with StatReloader
INFO 2025-01-17 19:56:53,731 autoreload 6336 8592 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 19:56:57,553 autoreload 3100 21656 Watching for file changes with StatReloader
ERROR 2025-01-17 19:57:17,039 views 3100 19452 YouTube download error: Song() got unexpected keyword arguments: 'thumbnail_url'
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 103, in download_youtube
    song = Song.objects.create(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: Song() got unexpected keyword arguments: 'thumbnail_url'
ERROR 2025-01-17 19:57:17,047 log 3100 19452 Internal Server Error: /api/songs/download/
ERROR 2025-01-17 19:57:17,048 basehttp 3100 19452 "POST /api/songs/download/ HTTP/1.1" 500 85
INFO 2025-01-17 20:16:47,617 autoreload 3100 21656 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 20:16:51,809 autoreload 7024 16788 Watching for file changes with StatReloader
INFO 2025-01-17 20:16:58,338 autoreload 7024 16788 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 20:17:02,297 autoreload 1444 22080 Watching for file changes with StatReloader
ERROR 2025-01-17 20:17:19,459 views 1444 20800 YouTube download error: Song() got unexpected keyword arguments: 'thumbnail_url'
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 105, in download_youtube
    song = Song.objects.create(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: Song() got unexpected keyword arguments: 'thumbnail_url'
ERROR 2025-01-17 20:17:19,463 log 1444 20800 Internal Server Error: /api/songs/download/
ERROR 2025-01-17 20:17:19,465 basehttp 1444 20800 "POST /api/songs/download/ HTTP/1.1" 500 85
INFO 2025-01-17 20:18:46,291 autoreload 8920 21464 Watching for file changes with StatReloader
INFO 2025-01-17 20:19:03,639 basehttp 8920 19920 "POST /api/songs/download/ HTTP/1.1" 200 4732460
INFO 2025-01-17 20:19:54,255 basehttp 8920 17136 "POST /api/songs/download/ HTTP/1.1" 200 8951084
INFO 2025-01-17 20:26:00,917 basehttp 8920 20344 "POST /api/songs/download/ HTTP/1.1" 200 12758444
INFO 2025-01-17 20:32:30,337 basehttp 8920 6172 "POST /api/songs/download/ HTTP/1.1" 200 12758444
INFO 2025-01-17 20:33:42,483 autoreload 8920 21464 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 20:33:46,826 autoreload 19148 14636 Watching for file changes with StatReloader
INFO 2025-01-17 20:33:52,159 autoreload 19148 14636 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 20:33:56,883 autoreload 2372 20564 Watching for file changes with StatReloader
INFO 2025-01-17 20:34:00,947 autoreload 2372 20564 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 20:34:05,361 autoreload 4320 22240 Watching for file changes with StatReloader
INFO 2025-01-17 20:34:46,786 basehttp 4320 22820 "POST /api/songs/download/ HTTP/1.1" 200 12758444
INFO 2025-01-17 20:35:15,510 autoreload 4320 22240 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 20:35:19,324 autoreload 22520 23456 Watching for file changes with StatReloader
INFO 2025-01-17 20:35:26,029 autoreload 22520 23456 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 20:35:30,710 autoreload 16548 22880 Watching for file changes with StatReloader
INFO 2025-01-17 20:36:04,451 basehttp 16548 20620 "POST /api/songs/download/ HTTP/1.1" 200 12758444
INFO 2025-01-17 20:37:39,805 basehttp 16548 11012 "POST /api/songs/download/ HTTP/1.1" 200 4732460
INFO 2025-01-17 20:38:27,597 autoreload 16548 22880 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 20:38:32,100 autoreload 20644 5904 Watching for file changes with StatReloader
INFO 2025-01-17 20:40:44,842 autoreload 20644 5904 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 20:40:49,171 autoreload 23256 21628 Watching for file changes with StatReloader
INFO 2025-01-17 20:40:55,547 autoreload 23256 21628 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 20:40:59,536 autoreload 22200 2908 Watching for file changes with StatReloader
INFO 2025-01-17 20:41:03,557 autoreload 22200 2908 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 20:41:07,604 autoreload 21688 23280 Watching for file changes with StatReloader
INFO 2025-01-17 20:42:38,753 basehttp 21688 21900 "POST /api/songs/download/ HTTP/1.1" 200 304
INFO 2025-01-17 20:44:06,964 autoreload 21688 23280 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 20:44:11,550 autoreload 22228 19596 Watching for file changes with StatReloader
INFO 2025-01-17 20:50:09,828 autoreload 22228 19596 D:\Projects\TuneVault\tunevault\tunevault\settings.py changed, reloading.
INFO 2025-01-17 20:50:13,755 autoreload 11608 16524 Watching for file changes with StatReloader
INFO 2025-01-17 20:50:41,909 basehttp 11608 17772 "POST /api/songs/download/ HTTP/1.1" 200 4732460
INFO 2025-01-17 20:52:28,859 basehttp 11608 19728 "POST /api/songs/download/ HTTP/1.1" 200 4173740
ERROR 2025-01-17 20:56:32,579 log 11608 13028 Internal Server Error: /api/songs/
Traceback (most recent call last):
  File "C:\Python 311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python 311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python 311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
           ^
  File "C:\Python 311\Lib\site-packages\rest_framework\serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\fields.py", line 1872, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\tunevault\songs\serializers.py", line 21, in get_image_url
    return obj.image
           ^^^^^^^^^
AttributeError: 'Song' object has no attribute 'image'
ERROR 2025-01-17 20:56:32,583 log 11608 5560 Internal Server Error: /api/songs/
Traceback (most recent call last):
  File "C:\Python 311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python 311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python 311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
           ^
  File "C:\Python 311\Lib\site-packages\rest_framework\serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\fields.py", line 1872, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\tunevault\songs\serializers.py", line 21, in get_image_url
    return obj.image
           ^^^^^^^^^
AttributeError: 'Song' object has no attribute 'image'
ERROR 2025-01-17 20:56:32,589 basehttp 11608 13028 "GET /api/songs/ HTTP/1.1" 500 147962
ERROR 2025-01-17 20:56:32,591 basehttp 11608 5560 "GET /api/songs/ HTTP/1.1" 500 147962
INFO 2025-01-17 21:23:15,952 autoreload 11608 16524 D:\Projects\TuneVault\tunevault\songs\serializers.py changed, reloading.
INFO 2025-01-17 21:23:20,973 autoreload 21380 8964 Watching for file changes with StatReloader
INFO 2025-01-17 21:23:32,912 autoreload 21380 8964 D:\Projects\TuneVault\tunevault\songs\models.py changed, reloading.
INFO 2025-01-17 21:23:37,141 autoreload 6052 19912 Watching for file changes with StatReloader
INFO 2025-01-17 21:34:01,398 autoreload 15672 7632 Watching for file changes with StatReloader
ERROR 2025-01-17 21:34:59,559 views 15672 4556 YouTube download error: column "song_url" of relation "songs_song" does not exist
LINE 1: ...ce", "spotify_id", "created_at", "thumbnail_url", "song_url"...
                                                             ^
Traceback (most recent call last):
  File "C:\Python 311\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column "song_url" of relation "songs_song" does not exist
LINE 1: ...ce", "spotify_id", "created_at", "thumbnail_url", "song_url"...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 104, in download_youtube
    song = Song.objects.create(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Python 311\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Python 311\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python 311\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Python 311\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Python 311\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column "song_url" of relation "songs_song" does not exist
LINE 1: ...ce", "spotify_id", "created_at", "thumbnail_url", "song_url"...
                                                             ^

ERROR 2025-01-17 21:34:59,649 log 15672 4556 Internal Server Error: /api/songs/download/
ERROR 2025-01-17 21:34:59,650 basehttp 15672 4556 "POST /api/songs/download/ HTTP/1.1" 500 241
INFO 2025-01-17 21:35:53,909 autoreload 1512 8792 Watching for file changes with StatReloader
INFO 2025-01-17 21:36:09,973 basehttp 1512 22624 "POST /api/songs/download/ HTTP/1.1" 200 4173740
INFO 2025-01-17 21:40:00,948 basehttp 1512 14792 "POST /api/songs/download/ HTTP/1.1" 200 4173740
INFO 2025-01-17 21:40:27,301 basehttp 1512 14792 "POST /api/songs/download/ HTTP/1.1" 200 4173740
INFO 2025-01-17 21:41:58,660 basehttp 1512 14792 "POST /api/songs/download/ HTTP/1.1" 200 4173740
INFO 2025-01-17 21:54:44,676 autoreload 1512 8792 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 21:54:49,108 autoreload 21324 7256 Watching for file changes with StatReloader
INFO 2025-01-17 22:01:31,109 autoreload 21324 7256 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 22:01:35,196 autoreload 18748 1236 Watching for file changes with StatReloader
INFO 2025-01-17 22:01:50,492 autoreload 18748 1236 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 22:01:54,622 autoreload 8704 17680 Watching for file changes with StatReloader
INFO 2025-01-17 22:03:50,788 autoreload 18496 1524 Watching for file changes with StatReloader
INFO 2025-01-17 22:08:48,834 autoreload 18496 1524 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 22:08:52,622 autoreload 22096 7324 Watching for file changes with StatReloader
INFO 2025-01-17 22:09:04,043 autoreload 22096 7324 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 22:09:07,845 autoreload 22960 12788 Watching for file changes with StatReloader
INFO 2025-01-17 22:09:14,429 autoreload 22960 12788 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 22:09:18,256 autoreload 20244 14684 Watching for file changes with StatReloader
INFO 2025-01-17 22:09:27,430 autoreload 20244 14684 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 22:09:31,351 autoreload 23040 21344 Watching for file changes with StatReloader
INFO 2025-01-17 22:09:46,656 autoreload 23040 21344 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 22:09:50,382 autoreload 20736 22448 Watching for file changes with StatReloader
INFO 2025-01-17 22:10:15,903 autoreload 20736 22448 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 22:10:19,635 autoreload 20868 22984 Watching for file changes with StatReloader
INFO 2025-01-17 22:10:29,754 autoreload 20868 22984 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 22:10:33,708 autoreload 6000 8880 Watching for file changes with StatReloader
INFO 2025-01-17 22:10:38,992 autoreload 6000 8880 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 22:10:42,942 autoreload 1904 22044 Watching for file changes with StatReloader
INFO 2025-01-17 22:13:51,431 autoreload 15652 23420 Watching for file changes with StatReloader
INFO 2025-01-17 22:28:48,715 autoreload 15652 23420 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 22:28:53,123 autoreload 2656 7884 Watching for file changes with StatReloader
ERROR 2025-01-17 22:29:00,619 log 2656 1316 Internal Server Error: /api/songs/download/
Traceback (most recent call last):
  File "C:\Python 311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\viewsets.py", line 116, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SongViewSet' object has no attribute 'download'
ERROR 2025-01-17 22:29:00,622 basehttp 2656 1316 "POST /api/songs/download/ HTTP/1.1" 500 20826
INFO 2025-01-17 22:29:20,717 autoreload 2656 7884 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 22:29:24,899 autoreload 4128 23316 Watching for file changes with StatReloader
INFO 2025-01-17 22:29:32,684 autoreload 4128 23316 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 22:29:36,768 autoreload 20144 20076 Watching for file changes with StatReloader
INFO 2025-01-17 22:29:48,542 autoreload 20144 20076 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 22:29:52,376 autoreload 11976 1316 Watching for file changes with StatReloader
INFO 2025-01-17 22:29:56,842 autoreload 11976 1316 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-17 22:30:01,405 autoreload 23500 22056 Watching for file changes with StatReloader
ERROR 2025-01-18 00:25:05,616 log 23500 23208 Internal Server Error: /api/songs/download/
Traceback (most recent call last):
  File "C:\Python 311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\viewsets.py", line 116, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SongViewSet' object has no attribute 'download'
ERROR 2025-01-18 00:25:07,359 basehttp 23500 23208 "POST /api/songs/download/ HTTP/1.1" 500 20826
ERROR 2025-01-18 00:25:16,333 log 23500 23208 Internal Server Error: /api/songs/download/
Traceback (most recent call last):
  File "C:\Python 311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\viewsets.py", line 116, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SongViewSet' object has no attribute 'download'
ERROR 2025-01-18 00:25:16,336 basehttp 23500 23208 "POST /api/songs/download/ HTTP/1.1" 500 20826
ERROR 2025-01-18 00:25:20,125 log 23500 23208 Internal Server Error: /api/songs/download/
Traceback (most recent call last):
  File "C:\Python 311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python 311\Lib\site-packages\rest_framework\viewsets.py", line 116, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SongViewSet' object has no attribute 'download'
ERROR 2025-01-18 00:25:20,130 basehttp 23500 23208 "POST /api/songs/download/ HTTP/1.1" 500 20826
INFO 2025-01-18 01:14:15,668 autoreload 4196 19992 Watching for file changes with StatReloader
INFO 2025-01-18 01:14:52,932 autoreload 4196 19992 D:\Projects\TuneVault\tunevault\songs\tasks.py changed, reloading.
INFO 2025-01-18 01:14:55,895 autoreload 22576 7456 Watching for file changes with StatReloader
INFO 2025-01-18 01:17:14,356 autoreload 20820 11816 Watching for file changes with StatReloader
INFO 2025-01-18 01:19:19,235 autoreload 22352 20172 Watching for file changes with StatReloader
INFO 2025-01-18 01:20:51,629 autoreload 22352 20172 D:\Projects\TuneVault\tunevault\tunevault\settings.py changed, reloading.
INFO 2025-01-18 01:20:54,697 autoreload 9248 13576 Watching for file changes with StatReloader
ERROR 2025-01-18 01:21:05,585 log 9248 5176 Internal Server Error: /api/songs/download/
Traceback (most recent call last):
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\viewsets.py", line 116, in view
    handler = getattr(self, action)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SongViewSet' object has no attribute 'download'
ERROR 2025-01-18 01:21:05,588 basehttp 9248 5176 "POST /api/songs/download/ HTTP/1.1" 500 20501
INFO 2025-01-18 01:22:38,350 autoreload 9248 13576 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-18 01:22:41,868 autoreload 5776 22736 Watching for file changes with StatReloader
INFO 2025-01-18 01:22:50,387 autoreload 5776 22736 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-18 01:22:53,594 autoreload 11848 19348 Watching for file changes with StatReloader
INFO 2025-01-18 01:24:00,928 autoreload 11848 19348 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-18 01:24:04,263 autoreload 18768 19592 Watching for file changes with StatReloader
ERROR 2025-01-18 01:24:35,961 views 18768 19956 Error embedding thumbnail: name 'ID3' is not defined
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 49, in embed_thumbnail_in_mp3
    audio = MP3(mp3_file_path, ID3=ID3)
                                   ^^^
NameError: name 'ID3' is not defined
INFO 2025-01-18 01:24:36,200 basehttp 18768 19956 "POST /api/songs/download/ HTTP/1.1" 200 6153452
INFO 2025-01-18 01:25:14,322 autoreload 18768 19592 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-18 01:25:17,193 autoreload 21164 18172 Watching for file changes with StatReloader
ERROR 2025-01-18 01:25:36,414 views 21164 21404 Error embedding thumbnail: 'Kiska Rasta Dekhe - Kishore Kumar (Reverb)' not a Frame instance
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 69, in embed_thumbnail_in_mp3
    audio.tags['TIT2'] = title
    ~~~~~~~~~~^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\mutagen\id3\_tags.py", line 341, in __setitem__
    raise TypeError("%r not a Frame instance" % tag)
TypeError: 'Kiska Rasta Dekhe - Kishore Kumar (Reverb)' not a Frame instance
INFO 2025-01-18 01:25:36,650 basehttp 21164 21404 "POST /api/songs/download/ HTTP/1.1" 200 6153452
ERROR 2025-01-18 01:26:12,320 views 21164 19036 Error embedding thumbnail: 'Chezile - Beanie (Official Live Video)' not a Frame instance
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 69, in embed_thumbnail_in_mp3
    audio.tags['TIT2'] = title
    ~~~~~~~~~~^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\mutagen\id3\_tags.py", line 341, in __setitem__
    raise TypeError("%r not a Frame instance" % tag)
TypeError: 'Chezile - Beanie (Official Live Video)' not a Frame instance
INFO 2025-01-18 01:26:12,513 basehttp 21164 19036 "POST /api/songs/download/ HTTP/1.1" 200 4732460
ERROR 2025-01-18 10:44:52,198 views 21164 7292 Error embedding thumbnail: 'Kiska Rasta Dekhe - Kishore Kumar (Reverb)' not a Frame instance
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 69, in embed_thumbnail_in_mp3
    audio.tags['TIT2'] = title
    ~~~~~~~~~~^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\mutagen\id3\_tags.py", line 341, in __setitem__
    raise TypeError("%r not a Frame instance" % tag)
TypeError: 'Kiska Rasta Dekhe - Kishore Kumar (Reverb)' not a Frame instance
INFO 2025-01-18 10:44:52,385 basehttp 21164 7292 "POST /api/songs/download/ HTTP/1.1" 200 6153452
ERROR 2025-01-18 11:32:39,356 views 21164 2228 Error embedding thumbnail: 'Time in a Bottle' not a Frame instance
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 69, in embed_thumbnail_in_mp3
    audio.tags['TIT2'] = title
    ~~~~~~~~~~^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\mutagen\id3\_tags.py", line 341, in __setitem__
    raise TypeError("%r not a Frame instance" % tag)
TypeError: 'Time in a Bottle' not a Frame instance
INFO 2025-01-18 11:32:39,498 basehttp 21164 2228 "POST /api/songs/download/ HTTP/1.1" 200 3567788
ERROR 2025-01-18 12:07:42,020 log 21164 13888 Internal Server Error: /api/songs/download/
Traceback (most recent call last):
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\backends\postgresql\base.py", line 332, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "ep-patient-resonance-a19rwm71.ap-southeast-1.aws.neon.tech" to address: No such host is known. 


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\request.py", line 231, in user
    self._authenticate()
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\authentication.py", line 196, in authenticate
    return self.authenticate_credentials(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\authentication.py", line 201, in authenticate_credentials
    token = model.objects.select_related('user').get(key=key)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\backends\base\base.py", line 320, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\backends\base\base.py", line 296, in _cursor
    self.ensure_connection()
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\backends\base\base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\backends\postgresql\base.py", line 332, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: could not translate host name "ep-patient-resonance-a19rwm71.ap-southeast-1.aws.neon.tech" to address: No such host is known. 

ERROR 2025-01-18 12:07:42,044 basehttp 21164 13888 "POST /api/songs/download/ HTTP/1.1" 500 27033
ERROR 2025-01-18 12:12:44,770 views 21164 12160 Error embedding thumbnail: 'Time in a Bottle' not a Frame instance
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 69, in embed_thumbnail_in_mp3
    audio.tags['TIT2'] = title
    ~~~~~~~~~~^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\mutagen\id3\_tags.py", line 341, in __setitem__
    raise TypeError("%r not a Frame instance" % tag)
TypeError: 'Time in a Bottle' not a Frame instance
INFO 2025-01-18 12:12:44,923 basehttp 21164 12160 "POST /api/songs/download/ HTTP/1.1" 200 3567788
ERROR 2025-01-18 12:13:51,333 views 21164 12160 Error embedding thumbnail: 'Time in a Bottle' not a Frame instance
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 69, in embed_thumbnail_in_mp3
    audio.tags['TIT2'] = title
    ~~~~~~~~~~^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\mutagen\id3\_tags.py", line 341, in __setitem__
    raise TypeError("%r not a Frame instance" % tag)
TypeError: 'Time in a Bottle' not a Frame instance
INFO 2025-01-18 12:13:51,456 basehttp 21164 12160 "POST /api/songs/download/ HTTP/1.1" 200 3567788
INFO 2025-01-18 12:14:07,759 autoreload 21164 18172 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-18 12:14:21,507 autoreload 12804 9684 Watching for file changes with StatReloader
INFO 2025-01-18 12:17:23,975 autoreload 12804 9684 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-18 12:17:27,384 autoreload 7016 21888 Watching for file changes with StatReloader
INFO 2025-01-18 12:17:31,976 autoreload 7016 21888 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-18 12:17:35,343 autoreload 6968 2848 Watching for file changes with StatReloader
INFO 2025-01-18 12:17:58,935 views 6968 22368 Successfully embedded thumbnail and metadata for: D:\Projects\TuneVault\tunevault\media\songs\Time in a Bottle.mp3
INFO 2025-01-18 12:17:59,159 basehttp 6968 22368 "POST /api/songs/download/ HTTP/1.1" 200 3614553
INFO 2025-01-18 12:18:36,248 autoreload 6968 2848 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-18 12:18:39,839 autoreload 6784 22028 Watching for file changes with StatReloader
INFO 2025-01-18 12:18:44,624 autoreload 6784 22028 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-18 12:18:48,229 autoreload 18396 11616 Watching for file changes with StatReloader
INFO 2025-01-18 12:19:06,180 autoreload 18396 11616 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-18 12:19:09,413 autoreload 19572 14444 Watching for file changes with StatReloader
INFO 2025-01-18 12:19:27,267 autoreload 19572 14444 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-18 12:19:30,489 autoreload 1220 1640 Watching for file changes with StatReloader
INFO 2025-01-18 12:19:53,814 autoreload 1220 1640 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-18 12:19:56,931 autoreload 21448 24236 Watching for file changes with StatReloader
INFO 2025-01-18 12:20:02,541 autoreload 21448 24236 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-18 12:20:05,689 autoreload 19052 19812 Watching for file changes with StatReloader
INFO 2025-01-18 12:20:26,555 views 19052 15368 Successfully embedded thumbnail and metadata for: D:\Projects\TuneVault\tunevault\media\songs\Time in a Bottle.mp3
INFO 2025-01-18 12:20:26,769 basehttp 19052 15368 "POST /api/songs/download/ HTTP/1.1" 200 3614553
ERROR 2025-01-18 13:24:24,553 log 19052 6624 Internal Server Error: /api/songs/download/
Traceback (most recent call last):
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\backends\postgresql\base.py", line 332, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "ep-patient-resonance-a19rwm71.ap-southeast-1.aws.neon.tech" to address: No such host is known. 


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\request.py", line 231, in user
    self._authenticate()
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\authentication.py", line 196, in authenticate
    return self.authenticate_credentials(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\authentication.py", line 201, in authenticate_credentials
    token = model.objects.select_related('user').get(key=key)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\backends\base\base.py", line 320, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\backends\base\base.py", line 296, in _cursor
    self.ensure_connection()
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\backends\base\base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\db\backends\postgresql\base.py", line 332, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: could not translate host name "ep-patient-resonance-a19rwm71.ap-southeast-1.aws.neon.tech" to address: No such host is known. 

ERROR 2025-01-18 13:24:24,566 basehttp 19052 6624 "POST /api/songs/download/ HTTP/1.1" 500 223595
INFO 2025-01-18 13:30:54,529 autoreload 19052 19812 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-18 13:31:08,396 autoreload 20440 14372 Watching for file changes with StatReloader
INFO 2025-01-19 22:32:15,201 autoreload 5140 17416 Watching for file changes with StatReloader
ERROR 2025-01-19 23:17:58,150 log 5140 19544 Internal Server Error: /api/songs/download/
Traceback (most recent call last):
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django_redis\cache.py", line 31, in _decorator
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django_redis\cache.py", line 98, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django_redis\client\default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 416, in initial
    self.check_throttles(request)
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\views.py", line 359, in check_throttles
    if not throttle.allow_request(request, self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\rest_framework\throttling.py", line 123, in allow_request
    self.history = self.cache.get(self.key, [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django_redis\cache.py", line 91, in get
    value = self._get(key, default, version, client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django_redis\cache.py", line 38, in _decorator
    raise e.__cause__
  File "D:\Projects\TuneVault\venv\Lib\site-packages\django_redis\client\default.py", line 258, in get
    value = client.get(key)
            ^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\redis\client.py", line 1606, in get
    return self.execute_command('GET', name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\redis\client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\venv\Lib\site-packages\redis\connection.py", line 1192, in get_connection
    connection.connect()
  File "D:\Projects\TuneVault\venv\Lib\site-packages\redis\connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.
ERROR 2025-01-19 23:17:58,197 basehttp 5140 19544 "POST /api/songs/download/ HTTP/1.1" 500 153312
INFO 2025-01-19 23:22:23,680 autoreload 22004 19544 Watching for file changes with StatReloader
ERROR 2025-01-19 23:23:17,570 views 22004 22520 YouTube download error: [Errno 2] No such file or directory: 'D:\\Projects\\TuneVault\\tunevault\\media\\songs\\Downloads.mp3'
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 256, in download_youtube
    open(filename, 'rb'),
    ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Projects\\TuneVault\\tunevault\\media\\songs\\Downloads.mp3'
ERROR 2025-01-19 23:23:17,625 log 22004 22520 Internal Server Error: /api/songs/download/
ERROR 2025-01-19 23:23:17,625 basehttp 22004 22520 "POST /api/songs/download/ HTTP/1.1" 500 143
INFO 2025-01-19 23:30:01,880 autoreload 22004 19544 D:\Projects\TuneVault\tunevault\songs\tasks.py changed, reloading.
INFO 2025-01-19 23:30:06,755 autoreload 19488 16964 Watching for file changes with StatReloader
INFO 2025-01-19 23:32:12,692 autoreload 19488 16964 D:\Projects\TuneVault\tunevault\songs\tasks.py changed, reloading.
INFO 2025-01-19 23:32:15,658 autoreload 15020 6288 Watching for file changes with StatReloader
INFO 2025-01-19 23:32:37,869 basehttp 15020 21988 "POST /api/songs/download/ HTTP/1.1" 202 125
WARNING 2025-01-19 23:34:01,430 log 15020 1148 Not Found: /api/songs/check_status/
WARNING 2025-01-19 23:34:01,434 basehttp 15020 1148 "POST //api/songs/check_status/?task_id=acf092ca-44f7-4114-b52d-d6c4ec2d3113 HTTP/1.1" 404 5563
INFO 2025-01-19 23:35:51,318 autoreload 15020 6288 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-19 23:35:54,803 autoreload 23452 11356 Watching for file changes with StatReloader
INFO 2025-01-19 23:40:42,894 autoreload 23452 11356 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-19 23:40:46,620 autoreload 7364 19580 Watching for file changes with StatReloader
INFO 2025-01-19 23:41:27,836 autoreload 7364 19580 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-19 23:41:31,158 autoreload 11172 12420 Watching for file changes with StatReloader
INFO 2025-01-19 23:42:55,646 autoreload 11172 12420 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-19 23:42:59,088 autoreload 17468 23252 Watching for file changes with StatReloader
INFO 2025-01-19 23:43:03,863 autoreload 17468 23252 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-19 23:43:07,304 autoreload 12812 7960 Watching for file changes with StatReloader
INFO 2025-01-19 23:43:19,969 autoreload 12812 7960 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-19 23:43:23,410 autoreload 8272 12584 Watching for file changes with StatReloader
INFO 2025-01-19 23:43:29,501 autoreload 8272 12584 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-19 23:43:32,747 autoreload 22336 5340 Watching for file changes with StatReloader
INFO 2025-01-19 23:43:38,934 autoreload 22336 5340 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-19 23:43:42,180 autoreload 13356 14552 Watching for file changes with StatReloader
INFO 2025-01-19 23:44:03,353 autoreload 13356 14552 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-19 23:44:06,588 autoreload 7960 17060 Watching for file changes with StatReloader
WARNING 2025-01-19 23:44:13,082 log 7960 22880 Not Found: /api/songs/check_status/
WARNING 2025-01-19 23:44:13,083 basehttp 7960 22880 "POST //api/songs/check_status/?task_id=acf092ca-44f7-4114-b52d-d6c4ec2d3113 HTTP/1.1" 404 5563
ERROR 2025-01-19 23:44:42,413 views 7960 22880 YouTube download error: name 'yt_dlp' is not defined
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 105, in download_youtube
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
         ^^^^^^
NameError: name 'yt_dlp' is not defined
ERROR 2025-01-19 23:44:42,438 log 7960 22880 Internal Server Error: /api/songs/download/
ERROR 2025-01-19 23:44:42,439 basehttp 7960 22880 "POST /api/songs/download/ HTTP/1.1" 500 57
INFO 2025-01-19 23:45:04,005 autoreload 7960 17060 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-19 23:45:07,272 autoreload 10484 17668 Watching for file changes with StatReloader
INFO 2025-01-19 23:48:31,072 autoreload 17260 2100 Watching for file changes with StatReloader
INFO 2025-01-19 23:49:55,584 basehttp 17260 21384 "POST /api/songs/download/ HTTP/1.1" 200 8334188
ERROR 2025-01-19 23:51:26,888 views 17260 18232 YouTube download error: [Errno 2] No such file or directory: 'D:\\Projects\\TuneVault\\tunevault\\media\\songs\\Downloads.mp3'
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 125, in download_youtube
    open(filename, 'rb'),
    ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Projects\\TuneVault\\tunevault\\media\\songs\\Downloads.mp3'
ERROR 2025-01-19 23:51:26,891 log 17260 18232 Internal Server Error: /api/songs/download/
ERROR 2025-01-19 23:51:26,892 basehttp 17260 18232 "POST /api/songs/download/ HTTP/1.1" 500 143
INFO 2025-01-19 23:58:51,628 autoreload 17260 2100 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-19 23:58:54,843 autoreload 14860 23244 Watching for file changes with StatReloader
INFO 2025-01-19 23:59:03,233 autoreload 14860 23244 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-19 23:59:07,011 autoreload 7012 23012 Watching for file changes with StatReloader
INFO 2025-01-19 23:59:31,007 basehttp 7012 11268 "POST /api/songs/download/ HTTP/1.1" 200 8334188
INFO 2025-01-20 00:14:56,815 autoreload 7012 23012 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-20 00:15:00,122 autoreload 11096 9560 Watching for file changes with StatReloader
INFO 2025-01-20 00:15:08,614 autoreload 11096 9560 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-20 00:15:11,621 autoreload 22948 23016 Watching for file changes with StatReloader
INFO 2025-01-20 00:15:16,438 autoreload 22948 23016 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-20 00:15:19,643 autoreload 19000 15212 Watching for file changes with StatReloader
INFO 2025-01-20 00:15:23,595 basehttp 19000 22004 "POST /api/songs/download/ HTTP/1.1" 202 125
INFO 2025-01-20 00:15:32,318 autoreload 19000 15212 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-20 00:15:35,474 autoreload 10916 22288 Watching for file changes with StatReloader
INFO 2025-01-20 00:17:00,435 autoreload 10916 22288 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-20 00:17:04,315 autoreload 23496 23520 Watching for file changes with StatReloader
INFO 2025-01-20 00:17:24,938 autoreload 23496 23520 D:\Projects\TuneVault\tunevault\songs\urls.py changed, reloading.
INFO 2025-01-20 00:17:28,289 autoreload 11676 23244 Watching for file changes with StatReloader
INFO 2025-01-20 00:20:57,038 autoreload 7592 6024 Watching for file changes with StatReloader
INFO 2025-01-20 00:21:17,567 autoreload 7592 6024 D:\Projects\TuneVault\tunevault\songs\urls.py changed, reloading.
INFO 2025-01-20 00:21:20,760 autoreload 21372 17068 Watching for file changes with StatReloader
INFO 2025-01-20 00:21:30,556 autoreload 21372 17068 D:\Projects\TuneVault\tunevault\songs\urls.py changed, reloading.
INFO 2025-01-20 00:21:34,150 autoreload 15580 1256 Watching for file changes with StatReloader
INFO 2025-01-20 00:21:40,053 basehttp 15580 4388 "POST /api/songs/download/ HTTP/1.1" 202 125
WARNING 2025-01-20 00:22:03,058 log 15580 4388 Method Not Allowed: /api/songs/check_status/
WARNING 2025-01-20 00:22:03,087 basehttp 15580 4388 "POST //api/songs/check_status/?task_id=c121a469-0de3-4daf-a826-d51fc29f6b2a HTTP/1.1" 405 41
INFO 2025-01-20 00:22:14,699 basehttp 15580 4388 "GET //api/songs/check_status/?task_id=c121a469-0de3-4daf-a826-d51fc29f6b2a HTTP/1.1" 200 48
INFO 2025-01-20 00:22:35,785 basehttp 15580 4388 "GET //api/songs/check_status/?task_id=c121a469-0de3-4daf-a826-d51fc29f6b2a HTTP/1.1" 200 48
INFO 2025-01-20 00:22:52,596 basehttp 15580 4388 "GET //api/songs/check_status/?task_id=c121a469-0de3-4daf-a826-d51fc29f6b2a HTTP/1.1" 200 48
INFO 2025-01-20 00:22:54,693 basehttp 15580 4388 "GET //api/songs/check_status/?task_id=c121a469-0de3-4daf-a826-d51fc29f6b2a HTTP/1.1" 200 48
INFO 2025-01-20 00:23:59,435 basehttp 15580 19708 "GET //api/songs/check_status/?task_id=c121a469-0de3-4daf-a826-d51fc29f6b2a HTTP/1.1" 200 48
INFO 2025-01-20 00:24:03,416 basehttp 15580 19708 "GET //api/songs/check_status/?task_id=c121a469-0de3-4daf-a826-d51fc29f6b2a HTTP/1.1" 200 48
INFO 2025-01-20 00:24:19,929 basehttp 15580 19708 "GET //api/songs/check_status/?task_id=c121a469-0de3-4daf-a826-d51fc29f6b2a HTTP/1.1" 200 48
INFO 2025-01-20 00:24:40,294 basehttp 15580 19708 "POST /api/songs/download/ HTTP/1.1" 202 125
INFO 2025-01-20 00:25:08,669 basehttp 15580 19708 "GET //api/songs/check_status/?task_id=c121a469-0de3-4daf-a826-d51fc29f6b2a HTTP/1.1" 200 48
INFO 2025-01-20 00:25:13,801 basehttp 15580 19708 "GET /api/songs/check_status/?task_id=c121a469-0de3-4daf-a826-d51fc29f6b2a HTTP/1.1" 200 48
INFO 2025-01-20 00:29:25,150 autoreload 15580 1256 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-20 00:29:28,297 autoreload 15020 21096 Watching for file changes with StatReloader
INFO 2025-01-20 00:31:59,348 autoreload 15020 21096 D:\Projects\TuneVault\tunevault\songs\urls.py changed, reloading.
INFO 2025-01-20 00:32:02,580 autoreload 20416 396 Watching for file changes with StatReloader
ERROR 2025-01-20 00:32:11,240 views 20416 22828 YouTube download error: name 'yt_dlp' is not defined
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 103, in download_youtube
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
         ^^^^^^
NameError: name 'yt_dlp' is not defined
ERROR 2025-01-20 00:32:11,243 log 20416 22828 Internal Server Error: /api/songs/download/
ERROR 2025-01-20 00:32:11,244 basehttp 20416 22828 "POST /api/songs/download/ HTTP/1.1" 500 57
INFO 2025-01-20 00:32:28,059 autoreload 20416 396 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-20 00:32:31,585 autoreload 17960 17464 Watching for file changes with StatReloader
INFO 2025-01-20 00:32:50,669 basehttp 17960 1976 "POST /api/songs/download/ HTTP/1.1" 200 5518124
INFO 2025-01-20 00:33:10,221 autoreload 17960 17464 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-20 00:33:13,859 autoreload 22260 17308 Watching for file changes with StatReloader
INFO 2025-01-20 00:33:22,632 basehttp 22260 21300 "POST /api/songs/download/ HTTP/1.1" 202 125
INFO 2025-01-20 00:34:43,385 autoreload 22260 17308 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-20 00:34:47,185 autoreload 18344 18768 Watching for file changes with StatReloader
INFO 2025-01-20 00:36:53,629 autoreload 18344 18768 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-20 00:36:57,145 autoreload 20896 16464 Watching for file changes with StatReloader
INFO 2025-01-20 00:37:15,817 basehttp 20896 22472 "POST /api/songs/download/ HTTP/1.1" 200 5518124
INFO 2025-01-20 00:37:58,044 basehttp 20896 22472 "POST /api/songs/download/ HTTP/1.1" 202 103
WARNING 2025-01-20 00:38:15,427 log 20896 22472 Method Not Allowed: /api/songs/download/
WARNING 2025-01-20 00:38:15,428 basehttp 20896 22472 "GET //api/songs/download/?task_id=a2b12c97-324e-44e8-956b-69e7748a7b36 HTTP/1.1" 405 40
WARNING 2025-01-20 00:38:37,866 log 20896 22472 Method Not Allowed: /api/songs/download/
WARNING 2025-01-20 00:38:37,867 basehttp 20896 22472 "GET /api/songs/download/?task_id=a2b12c97-324e-44e8-956b-69e7748a7b36 HTTP/1.1" 405 40
INFO 2025-01-20 00:39:42,220 autoreload 20896 16464 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-20 00:39:45,467 autoreload 17480 22116 Watching for file changes with StatReloader
WARNING 2025-01-20 00:39:50,890 log 17480 15656 Method Not Allowed: /api/songs/download/
WARNING 2025-01-20 00:39:50,891 basehttp 17480 15656 "GET /api/songs/download/?task_id=a2b12c97-324e-44e8-956b-69e7748a7b36 HTTP/1.1" 405 40
ERROR 2025-01-20 00:40:27,970 views 17480 15656 Error checking task status: name 'DownloadProgress' is not defined
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 230, in check_status
    progress = DownloadProgress.objects.filter(task_id=task_id).first()
               ^^^^^^^^^^^^^^^^
NameError: name 'DownloadProgress' is not defined
ERROR 2025-01-20 00:40:27,972 log 17480 15656 Internal Server Error: /api/songs/check_status/
ERROR 2025-01-20 00:40:27,973 basehttp 17480 15656 "GET /api/songs/check_status/?task_id=a2b12c97-324e-44e8-956b-69e7748a7b36 HTTP/1.1" 500 71
INFO 2025-01-20 00:41:02,491 autoreload 17480 22116 D:\Projects\TuneVault\tunevault\songs\models.py changed, reloading.
INFO 2025-01-20 00:41:39,586 autoreload 17996 18484 Watching for file changes with StatReloader
INFO 2025-01-20 00:41:46,780 basehttp 17996 17700 "POST /api/songs/download/ HTTP/1.1" 202 103
ERROR 2025-01-20 00:41:59,847 views 17996 17700 Error checking task status: name 'DownloadProgress' is not defined
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 230, in check_status
    progress = DownloadProgress.objects.filter(task_id=task_id).first()
               ^^^^^^^^^^^^^^^^
NameError: name 'DownloadProgress' is not defined
ERROR 2025-01-20 00:41:59,849 log 17996 17700 Internal Server Error: /api/songs/check_status/
ERROR 2025-01-20 00:41:59,850 basehttp 17996 17700 "GET /api/songs/check_status/?task_id=2126d9e7-1ece-4b35-a244-a2e736d31131 HTTP/1.1" 500 71
ERROR 2025-01-20 00:42:03,680 views 17996 17700 Error checking task status: name 'DownloadProgress' is not defined
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 230, in check_status
    progress = DownloadProgress.objects.filter(task_id=task_id).first()
               ^^^^^^^^^^^^^^^^
NameError: name 'DownloadProgress' is not defined
ERROR 2025-01-20 00:42:03,681 log 17996 17700 Internal Server Error: /api/songs/check_status/
ERROR 2025-01-20 00:42:03,682 basehttp 17996 17700 "GET /api/songs/check_status/?task_id=2126d9e7-1ece-4b35-a244-a2e736d31131 HTTP/1.1" 500 71
INFO 2025-01-20 00:42:18,106 autoreload 17996 18484 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-20 00:42:21,226 autoreload 22028 4704 Watching for file changes with StatReloader
INFO 2025-01-20 00:42:27,883 basehttp 22028 3300 "GET /api/songs/check_status/?task_id=2126d9e7-1ece-4b35-a244-a2e736d31131 HTTP/1.1" 200 41
INFO 2025-01-20 00:43:42,064 basehttp 22028 712 "GET /api/songs/check_status/?task_id=2126d9e7-1ece-4b35-a244-a2e736d31131 HTTP/1.1" 200 41
INFO 2025-01-20 00:43:45,313 basehttp 22028 712 "GET /api/songs/check_status/?task_id=2126d9e7-1ece-4b35-a244-a2e736d31131 HTTP/1.1" 200 41
INFO 2025-01-20 00:45:19,784 basehttp 22028 22776 "GET /api/songs/check_status/?task_id=2126d9e7-1ece-4b35-a244-a2e736d31131 HTTP/1.1" 200 41
INFO 2025-01-20 00:50:17,216 autoreload 22028 4704 D:\Projects\TuneVault\tunevault\songs\tasks.py changed, reloading.
INFO 2025-01-20 00:50:20,423 autoreload 7912 21000 Watching for file changes with StatReloader
INFO 2025-01-20 00:52:10,950 basehttp 7912 19088 "POST /api/songs/download/ HTTP/1.1" 202 103
INFO 2025-01-20 00:52:26,821 basehttp 7912 19088 "GET /api/songs/check_status/?task_id=fc4b0c2e-daae-4b7a-8a04-f2a718d9b73e HTTP/1.1" 200 41
INFO 2025-01-20 00:52:29,307 basehttp 7912 19088 "GET /api/songs/check_status/?task_id=fc4b0c2e-daae-4b7a-8a04-f2a718d9b73e HTTP/1.1" 200 41
INFO 2025-01-20 00:52:34,339 basehttp 7912 19088 "GET /api/songs/check_status/?task_id=fc4b0c2e-daae-4b7a-8a04-f2a718d9b73e HTTP/1.1" 200 41
INFO 2025-01-20 00:52:36,444 basehttp 7912 19088 "GET /api/songs/check_status/?task_id=fc4b0c2e-daae-4b7a-8a04-f2a718d9b73e HTTP/1.1" 200 41
INFO 2025-01-20 00:52:38,384 basehttp 7912 19088 "GET /api/songs/check_status/?task_id=fc4b0c2e-daae-4b7a-8a04-f2a718d9b73e HTTP/1.1" 200 41
INFO 2025-01-20 00:52:40,451 basehttp 7912 19088 "GET /api/songs/check_status/?task_id=fc4b0c2e-daae-4b7a-8a04-f2a718d9b73e HTTP/1.1" 200 41
INFO 2025-01-20 00:54:41,078 autoreload 7912 21000 D:\Projects\TuneVault\tunevault\songs\tasks.py changed, reloading.
INFO 2025-01-20 00:54:44,401 autoreload 3820 1164 Watching for file changes with StatReloader
INFO 2025-01-20 00:54:50,501 basehttp 3820 6912 "GET /api/songs/check_status/?task_id=fc4b0c2e-daae-4b7a-8a04-f2a718d9b73e HTTP/1.1" 200 41
INFO 2025-01-20 00:54:54,752 basehttp 3820 6912 "POST /api/songs/download/ HTTP/1.1" 202 117
INFO 2025-01-20 00:55:06,842 basehttp 3820 6912 "GET /api/songs/check_status/?task_id=fa615959-f240-4a03-97f2-7496d3338819 HTTP/1.1" 200 41
INFO 2025-01-20 00:55:09,143 basehttp 3820 6912 "GET /api/songs/check_status/?task_id=fa615959-f240-4a03-97f2-7496d3338819 HTTP/1.1" 200 41
INFO 2025-01-20 00:55:15,044 basehttp 3820 6912 "POST /api/songs/download/ HTTP/1.1" 202 117
INFO 2025-01-20 00:55:25,428 basehttp 3820 6912 "POST /api/songs/download/ HTTP/1.1" 202 117
INFO 2025-01-20 00:55:42,394 autoreload 3820 1164 D:\Projects\TuneVault\tunevault\songs\tasks.py changed, reloading.
INFO 2025-01-20 00:55:45,661 autoreload 17332 22608 Watching for file changes with StatReloader
INFO 2025-01-20 00:55:52,973 basehttp 17332 19356 "POST /api/songs/download/ HTTP/1.1" 202 117
INFO 2025-01-20 00:55:57,081 autoreload 17332 22608 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-20 00:56:00,609 autoreload 8068 23348 Watching for file changes with StatReloader
INFO 2025-01-20 00:56:15,745 basehttp 8068 13240 "POST /api/songs/download/ HTTP/1.1" 200 5518124
ERROR 2025-01-20 00:57:18,474 views 8068 5704 Spotify track download error: 'SongViewSet' object has no attribute 'get_track_info'
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 77, in download_spotify_track
    track_info = self.get_track_info(url)  # You'll need to implement this method
                 ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SongViewSet' object has no attribute 'get_track_info'
ERROR 2025-01-20 00:57:18,474 views 8068 5704 Download error: 'SongViewSet' object has no attribute 'get_track_info'
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 171, in download
    return self.download_spotify_track(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 77, in download_spotify_track
    track_info = self.get_track_info(url)  # You'll need to implement this method
                 ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SongViewSet' object has no attribute 'get_track_info'
ERROR 2025-01-20 00:57:18,474 log 8068 5704 Internal Server Error: /api/songs/download/
ERROR 2025-01-20 00:57:18,474 basehttp 8068 5704 "POST /api/songs/download/ HTTP/1.1" 500 83
INFO 2025-01-20 00:57:41,424 autoreload 8068 23348 D:\Projects\TuneVault\tunevault\songs\tasks.py changed, reloading.
INFO 2025-01-20 00:57:45,161 autoreload 22776 8052 Watching for file changes with StatReloader
INFO 2025-01-20 00:57:52,517 autoreload 22776 8052 D:\Projects\TuneVault\tunevault\songs\tasks.py changed, reloading.
INFO 2025-01-20 00:57:55,570 autoreload 6912 21472 Watching for file changes with StatReloader
ERROR 2025-01-20 00:58:13,330 views 6912 14940 Spotify track download error: 'SongViewSet' object has no attribute 'get_track_info'
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 77, in download_spotify_track
    track_info = self.get_track_info(url)  # You'll need to implement this method
                 ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SongViewSet' object has no attribute 'get_track_info'
ERROR 2025-01-20 00:58:13,420 views 6912 14940 Download error: 'SongViewSet' object has no attribute 'get_track_info'
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 171, in download
    return self.download_spotify_track(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 77, in download_spotify_track
    track_info = self.get_track_info(url)  # You'll need to implement this method
                 ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SongViewSet' object has no attribute 'get_track_info'
ERROR 2025-01-20 00:58:13,421 log 6912 14940 Internal Server Error: /api/songs/download/
ERROR 2025-01-20 00:58:13,422 basehttp 6912 14940 "POST /api/songs/download/ HTTP/1.1" 500 83
INFO 2025-01-20 00:58:24,957 autoreload 6912 21472 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-20 00:58:27,983 autoreload 7760 7012 Watching for file changes with StatReloader
ERROR 2025-01-20 00:58:44,804 views 7760 7080 Spotify track download error: 'SongViewSet' object has no attribute 'get_track_info'
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 79, in download_spotify_track
    track_info = self.get_track_info(url)  # You'll need to implement this method
                 ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SongViewSet' object has no attribute 'get_track_info'
ERROR 2025-01-20 00:58:44,804 views 7760 7080 Download error: 'SongViewSet' object has no attribute 'get_track_info'
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 173, in download
    return self.download_spotify_track(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 79, in download_spotify_track
    track_info = self.get_track_info(url)  # You'll need to implement this method
                 ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SongViewSet' object has no attribute 'get_track_info'
ERROR 2025-01-20 00:58:44,804 log 7760 7080 Internal Server Error: /api/songs/download/
ERROR 2025-01-20 00:58:44,804 basehttp 7760 7080 "POST /api/songs/download/ HTTP/1.1" 500 83
ERROR 2025-01-20 00:58:47,026 views 7760 7080 Spotify track download error: 'SongViewSet' object has no attribute 'get_track_info'
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 79, in download_spotify_track
    track_info = self.get_track_info(url)  # You'll need to implement this method
                 ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SongViewSet' object has no attribute 'get_track_info'
ERROR 2025-01-20 00:58:47,026 views 7760 7080 Download error: 'SongViewSet' object has no attribute 'get_track_info'
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 173, in download
    return self.download_spotify_track(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 79, in download_spotify_track
    track_info = self.get_track_info(url)  # You'll need to implement this method
                 ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SongViewSet' object has no attribute 'get_track_info'
ERROR 2025-01-20 00:58:47,026 log 7760 7080 Internal Server Error: /api/songs/download/
ERROR 2025-01-20 00:58:47,026 basehttp 7760 7080 "POST /api/songs/download/ HTTP/1.1" 500 83
INFO 2025-01-20 00:58:57,972 autoreload 7760 7012 D:\Projects\TuneVault\tunevault\songs\views.py changed, reloading.
INFO 2025-01-20 00:59:01,332 autoreload 23252 21260 Watching for file changes with StatReloader
INFO 2025-01-20 00:59:21,170 basehttp 23252 22520 "POST /api/songs/download/ HTTP/1.1" 200 6185708
INFO 2025-01-20 01:00:55,231 basehttp 23252 880 "POST /api/songs/download/ HTTP/1.1" 202 112
WARNING 2025-01-20 01:01:41,479 log 23252 880 Method Not Allowed: /api/songs/download/
WARNING 2025-01-20 01:01:41,481 basehttp 23252 880 "GET /api/songs/download/?task_id=9bcb8238-73b9-48ec-b73d-6ae7d8bfa203 HTTP/1.1" 405 40
INFO 2025-01-20 01:02:11,374 autoreload 22808 14416 Watching for file changes with StatReloader
ERROR 2025-01-20 01:03:03,849 views 22808 6780 YouTube download error: [Errno 2] No such file or directory: 'D:\\Projects\\TuneVault\\tunevault\\media\\songs\\Downloads.mp3'
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 65, in download_youtube
    open(filename, 'rb'),
    ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Projects\\TuneVault\\tunevault\\media\\songs\\Downloads.mp3'
ERROR 2025-01-20 01:03:03,853 views 22808 6780 Download error: [Errno 2] No such file or directory: 'D:\\Projects\\TuneVault\\tunevault\\media\\songs\\Downloads.mp3'
Traceback (most recent call last):
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 154, in download
    return self.download_youtube(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\TuneVault\tunevault\songs\views.py", line 65, in download_youtube
    open(filename, 'rb'),
    ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Projects\\TuneVault\\tunevault\\media\\songs\\Downloads.mp3'
ERROR 2025-01-20 01:03:03,855 log 22808 6780 Internal Server Error: /api/songs/download/
ERROR 2025-01-20 01:03:03,856 basehttp 22808 6780 "POST /api/songs/download/ HTTP/1.1" 500 143
